### ISSUE TITLE
[BUG]: Render disparity between two Animate versions

### ISSUE THREAD

**Issue by ACrazyTown** [Dot-Stuff/flxanimate#18]
**Describe the bug**
While I was testing around some stuff with FlxAnimate I found out that the same symbol renders differently from two different Animate CC versions.

**Explain how to recreate the bug**
Might not work with all symbols, but export a texture atlas from Animate 2019 & 2021 and display them using the following code:
```haxe
var animTest:FlxAnimate = new FlxAnimate(50, 50, "[Path]", {Antialiasing: true});
animTest.anim.addBySymbol("a", "[Symbol Name]", 24, true);
add(animTest);

animTest.anim.play("a");
```

**What should happen?**
The symbols should display identically.

**Adobe Animate Version**
Animate CC 2019 19.2.1 (build 408)
Animate CC 2021 21.0.6 (build 41649)
FlxAnimate version is the one from Haxelib

**Additional context**
How it displays when exported from Animate 2021:
![image](https://user-images.githubusercontent.com/47027981/197397590-d9c98ffd-c9a2-4b40-9eb1-6b6572486f87.png)

How it displays when exported from Animate 2019:
![image](https://user-images.githubusercontent.com/47027981/197397640-756cbe9c-dead-4e01-805f-8ae6d0b7894b.png)

Files for both texture atlases
2019: https://cdn.discordapp.com/attachments/1006517991531368558/1033747631295443005/halloween_oceanrant.zip
2021: https://cdn.discordapp.com/attachments/1006517991531368558/1033747631685509223/halloweenAn21.zip

I can also provide the fla if it can help out with debugging.

**Comment by ACrazyTown** [comment]
I'm gonna investigate this a bit more, but as of right now I've found out that Animate 2020 displays identically to Animate 2021

**Comment by ACrazyTown** [comment]
I figured it out!!! sort of. 
![image](https://user-images.githubusercontent.com/47027981/201487025-4c8fb678-f3c8-4336-9cd6-9e27403a7f09.png)

The eyes didn't display in 2021 because they were a "Drawing object", I'm guessing FlxAnimate can't parse these yet? The anim plays fine, except for the border shape which wobbles around when the character moves.

**Comment by Cheemsandfriends** [comment]
Would you please provide the fla which contains this animation?
I am sorry for not replying sooner about this matter, but I was already occupied with making the new version of FlxAnimate.

Thanks for your time and sorry for the inconvenience.

**Comment by ACrazyTown** [comment]
> Would you please provide the fla which contains this animation? I am sorry for not replying sooner about this matter, but I was already occupied with making the new version of FlxAnimate.
> 
> Thanks for your time and sorry for the inconvenience.

I'll send you it on discord

**Comment by Cheemsandfriends** [comment]
I sent a message regarding this issue already on Discord, but I believe this would be good to send it here too to have a record.

"The eyes don't seem to be rendering correctly because, to put it in a way, the eyes are connected to the legs and arms as a whole sprite
from what I can tell, Drawing Objects are just a fancy way to group drawings but not animations, and so in texture atlas it seems to just overlook that and think it's all a single drawing, and it misleads Adobe Animate
the wobbly border is a render error in the matrix (as weird as it can sound) it's basically a render error which basically, the texture atlas is rounding the matrix values."

Again, I am sorry for not being able to help, but this seems that Adobe Animate isn't rendering the texture atlases properly.

**Comment by ACrazyTown** [comment]
Closing because this is more of an Animate issue rather than a FlxAnimate issue
