### ISSUE TITLE
so like

### ISSUE THREAD

**Issue by Zoardedz** [Dot-Stuff/flxanimate#19]
if you have multiple frames for one animation and the play function only plays one frame, how would you play all the frames, i don't get it here do i somehow have to count each frame then make a for loop which i play that frame inside the loop or what? i don't get the point of making it play a SPECIFIC frame

**Comment by Cheemsandfriends** [comment]
I would want to clear up some things.

First of all, the function `play()` plays all the frames in order faster or slower depending on the framerate, all in a row or several rows depending if you want to loop it or not.

Second of all, I would want to see some code of how you instantiated `FlxAnimate` and how you tried to play the atlas animation in question.

Last of all, I would want to know which version of Adobe Animate you exported the atlas and the version of FlxAnimate itself (This is to check that you're currently using the most recent one).

The information that I ask is needed so that I could recreate it and fix it. If you wanna help the recreation of the error to be quicker, you could always give the atlas that you're trying with and it would be appreciated!

I sincerely apologise for all the inconveniences that you might have with FlxAnimate and I hope you can understand 🙂

**Comment by Zoardedz** [comment]
alright heres the code, 
![image](https://user-images.githubusercontent.com/92955177/198847874-d110c0be-9c5c-420a-a882-fc08f8bcb9e3.png)
and i dont know what version it was exported in, as this is from the hypno's lullaby mod but it renders successfully as follows:
![image](https://user-images.githubusercontent.com/92955177/198847904-73fbd8ea-670b-4f6f-8d9b-7436dcdab7dd.png)
heres the files: https://drive.google.com/file/d/1i5Kd4QiCfmTApJPGTW_hHsOtcmgKV84H/view?usp=sharing

**Comment by Zoardedz** [comment]
i figured it out, i had to do playerBackground.updateAnimation(elapsed);
